# Generated by Django 3.2.3 on 2021-06-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0002_rename_user_customer_userr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='userr',
            new_name='user',
        ),
    ]
