# Generated by Django 3.2.3 on 2021-06-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0003_rename_userr_customer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
