# Generated by Django 3.2.3 on 2021-06-23 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Message', models.TextField(max_length=500)),
                ('Date', models.DateTimeField(verbose_name=datetime.datetime(2021, 6, 23, 8, 2, 23, 174732))),
            ],
        ),
    ]
